namespace Carp;

using Antlr4.Runtime;
using exceptions;
using interpreter.execution;
using interpreter.visitors;
using objects;
using objects.typing;
using scoping;

public class Runtime
{
    public static Scope MakeScope(CarpType[] types)
    {
        Scope s = new();
        foreach (CarpType type in types)
            s.Define(new FieldMember(type.Name, CarpType.Type, type).With(Modifiers.Final));

        s.Define(new MethodMember("print", new NativeFunction(CarpVoid.Type, objs =>
        {
            foreach (CarpObject obj in objs)
                Console.Write(obj.String().Value);
            Console.WriteLine();
            return CarpVoid.Instance;
        })));

        return s;
    }

    /// <summary>
    /// </summary>
    /// <param name="executionContext"></param>
    /// <param name="scope">
    ///     Global scope to operate within, if not provided, one will be generated by <see cref="MakeScope" />
    /// </param>
    /// <returns>CarpObject based on the last expression, may be void</returns>
    /// <exception cref="ParserException">Thrown when syntax issue is detected at the parser step</exception>
    /// <exception cref="InterpreterException">Thrown when issue with ast-gen step</exception>
    /// <exception cref="RuntimeException">Thrown when carp-level code errors, at the interpreter step</exception>
    public static CarpObject Execute(IExecutionContext executionContext, Scope? scope = null)
    {
        CarpGrammarParser.ProgramContext program = null;
        try
        {
            AntlrInputStream stream = new(executionContext.GetContent());
            CarpGrammarLexer lexer = new(stream);
            lexer.RemoveErrorListeners();
            CommonTokenStream tokens = new(lexer);

            CarpGrammarParser parser = new(tokens);
            program = parser.program();
        }
        catch (Exception e)
        {
            throw new ParserException("Failed to parse the program.", e);
        }

        if (program == null)
            throw new ParserException("Failed to parse the program.");

        program.Scope = scope ?? Runtime.MakeScope(CarpType.ConstructTypes());
        program.ExecutionContext = executionContext;

        CarpVisitor visitor = new();
        CarpObject? output = visitor.Visit(program) as CarpObject;
        if (output == null)
            throw new InterpreterException("Failed to visit the program.");

        return output;
    }
}

public class ParserException(string message, Exception? ex = null)
    : Exception(message, ex);