namespace Carp;

using System.Reflection;
using Antlr4.Runtime;
using exceptions;
using interpreter.execution;
using interpreter.visitors;
using libraries.std.io;
using objects;
using objects.typing;
using scoping;
using toolkit;

public class Runtime
{
    public static Scope MakeScope(CarpType[] types)
    {
        Scope s = new();
        foreach (CarpType type in types)
            s.Define(new FieldMember(type.Name, CarpType.Type, type).With(Modifiers.Final));

        return s;
    }

    /// <summary>
    /// </summary>
    /// <param name="executionContext"></param>
    /// <param name="scope">
    ///     Global scope to operate within, if not provided, one will be generated by <see cref="MakeScope" />
    /// </param>
    /// <returns>CarpObject based on the last expression, may be void</returns>
    /// <exception cref="ParserException">Thrown when syntax issue is detected at the parser step</exception>
    /// <exception cref="InterpreterException">Thrown when issue with ast-gen step</exception>
    /// <exception cref="RuntimeException">Thrown when carp-level code errors, at the interpreter step</exception>
    public static CarpObject Execute(IExecutionContext executionContext, Scope? scope = null)
    {
        CommonTokenStream tokens = Runtime.Lex(executionContext);
        CarpGrammarParser.ProgramContext ast = Runtime.Parse(tokens, executionContext);
        return Runtime.Execute(ast, executionContext, scope);
    }

    /// <summary>
    /// </summary>
    /// <param name="parsedContext"></param>
    /// <param name="executionContext"></param>
    /// <param name="scope">
    ///     Global scope to operate within, if not provided, one will be generated by <see cref="MakeScope" />
    /// </param>
    /// <returns>CarpObject based on the last expression, may be void</returns>
    /// <exception cref="ParserException">Thrown when syntax issue is detected at the parser step</exception>
    /// <exception cref="InterpreterException">Thrown when issue with ast-gen step</exception>
    /// <exception cref="RuntimeException">Thrown when carp-level code errors, at the interpreter step</exception>
    public static CarpObject Execute(
        CarpGrammarParser.ProgramContext parsedContext,
        IExecutionContext executionContext,
        Scope? scope = null)
    {
        parsedContext.Scope = scope ?? Runtime.MakeScope(CarpType.ConstructTypes());
        parsedContext.ExecutionContext = executionContext;

        parsedContext.LibraryLoader = new();
        parsedContext.LibraryLoader.Load(new NativeLibrary(Assembly.GetExecutingAssembly(), "Carp.libraries"));

        CarpVisitor visitor = new();
        CarpObject? output = visitor.Visit(parsedContext) as CarpObject;
        if (output == null)
            throw new InterpreterException("Failed to visit the program.");

        return output;
    }

    /// <summary>
    /// Parses the content of the execution context into a CarpGrammarParser.ProgramContext.
    /// </summary>
    /// <param name="tokens"></param>
    /// <param name="executionContext">Execution context containing the content to parse.</param>
    /// <returns></returns>
    /// <exception cref="ParserException"></exception>
    public static CarpGrammarParser.ProgramContext Parse(CommonTokenStream tokens, IExecutionContext executionContext)
    {
        CarpGrammarParser.ProgramContext? program = null;
        try
        {
            CarpGrammarParser parser = new(tokens);
            program = parser.program();
        }
        catch (Exception e)
        {
            throw new ParserException("Failed to parse the program.", e);
        }

        if (program == null)
            throw new ParserException("Failed to parse the program.");

        return program;
    }
    public static CommonTokenStream Lex(IExecutionContext executionContext)
    {
        try
        {
            AntlrInputStream stream = new(executionContext.GetContent());
            CarpGrammarLexer lexer = new(stream);
            lexer.RemoveErrorListeners();
            CommonTokenStream tokens = new(lexer);
            tokens.Fill();
            tokens.Seek(0);
            return tokens;
        }
        catch (Exception e)
        {
            throw new ParserException("Failed to lex the program.", e);
        }
    }
}